# Generated by Django 2.0.3 on 2018-05-03 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='breed',
            name='slug',
            field=models.SlugField(default=' ', max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
